/* Shared vocabulary for Topic Match, Mixed Match and both typing games.
   To add a word, copy one word line inside the right topic and edit its values. */
window.MANDARIN_TOPICS = [
  { id: "numbers", name: "Numbers", emoji: "🔢", sub: "One to ten", words: [
    { id: "numbers:yī", hanzi: "一", pinyin: "yī", english: "one", pronunciation: "ee", accepted: ["1"] },
    { id: "numbers:èr", hanzi: "二", pinyin: "èr", english: "two", pronunciation: "arr", accepted: ["2"] },
    { id: "numbers:sān", hanzi: "三", pinyin: "sān", english: "three", pronunciation: "sahn", accepted: ["3"] },
    { id: "numbers:sì", hanzi: "四", pinyin: "sì", english: "four", pronunciation: "suh", accepted: ["4"] },
    { id: "numbers:wǔ", hanzi: "五", pinyin: "wǔ", english: "five", pronunciation: "woo", accepted: ["5"] },
    { id: "numbers:liù", hanzi: "六", pinyin: "liù", english: "six", pronunciation: "lyoh", accepted: ["6"] },
    { id: "numbers:qī", hanzi: "七", pinyin: "qī", english: "seven", pronunciation: "chee", accepted: ["7"] },
    { id: "numbers:bā", hanzi: "八", pinyin: "bā", english: "eight", pronunciation: "bah", accepted: ["8"] },
    { id: "numbers:jiǔ", hanzi: "九", pinyin: "jiǔ", english: "nine", pronunciation: "jyoh", accepted: ["9"] },
    { id: "numbers:shí", hanzi: "十", pinyin: "shí", english: "ten", pronunciation: "shrr", accepted: ["10"] },
  ] },
  { id: "adjectives", name: "Basic adjectives", emoji: "✨", sub: "Big, small, hot, cold…", words: [
    { id: "adjectives:dà", hanzi: "大", pinyin: "dà", english: "big", pronunciation: "dah", accepted: ["large"] },
    { id: "adjectives:xiǎo", hanzi: "小", pinyin: "xiǎo", english: "small", pronunciation: "shyow", accepted: ["little"] },
    { id: "adjectives:hǎo", hanzi: "好", pinyin: "hǎo", english: "good", pronunciation: "how", accepted: [] },
    { id: "adjectives:rè", hanzi: "热", pinyin: "rè", english: "hot", pronunciation: "ruh", accepted: [] },
    { id: "adjectives:lěng", hanzi: "冷", pinyin: "lěng", english: "cold", pronunciation: "lung", accepted: [] },
    { id: "adjectives:duō", hanzi: "多", pinyin: "duō", english: "many", pronunciation: "dwaw", accepted: ["a lot","lots","much"] },
    { id: "adjectives:kuài", hanzi: "快", pinyin: "kuài", english: "fast", pronunciation: "kwye", accepted: ["quick"] },
    { id: "adjectives:màn", hanzi: "慢", pinyin: "màn", english: "slow", pronunciation: "mahn", accepted: [] },
    { id: "adjectives:xīn", hanzi: "新", pinyin: "xīn", english: "new", pronunciation: "sheen", accepted: [] },
    { id: "adjectives:lèi", hanzi: "累", pinyin: "lèi", english: "tired", pronunciation: "lay", accepted: [] },
  ] },
  { id: "verbs", name: "Basic verbs", emoji: "🏃", sub: "Eat, drink, go, want…", words: [
    { id: "verbs:chī", hanzi: "吃", pinyin: "chī", english: "to eat", pronunciation: "chrr", accepted: [] },
    { id: "verbs:hē", hanzi: "喝", pinyin: "hē", english: "to drink", pronunciation: "huh", accepted: [] },
    { id: "verbs:qù", hanzi: "去", pinyin: "qù", english: "to go", pronunciation: "chyoo", accepted: [] },
    { id: "verbs:lái", hanzi: "来", pinyin: "lái", english: "to come", pronunciation: "lye", accepted: [] },
    { id: "verbs:yào", hanzi: "要", pinyin: "yào", english: "to want", pronunciation: "yow", accepted: ["would like"] },
    { id: "verbs:yǒu", hanzi: "有", pinyin: "yǒu", english: "to have", pronunciation: "yoh", accepted: [] },
    { id: "verbs:kàn", hanzi: "看", pinyin: "kàn", english: "to look / see", pronunciation: "kahn", accepted: ["look","see","watch"] },
    { id: "verbs:shuō", hanzi: "说", pinyin: "shuō", english: "to speak", pronunciation: "shwaw", accepted: ["talk","say"] },
    { id: "verbs:mǎi", hanzi: "买", pinyin: "mǎi", english: "to buy", pronunciation: "my", accepted: [] },
    { id: "verbs:ài", hanzi: "爱", pinyin: "ài", english: "to love", pronunciation: "eye", accepted: [] },
  ] },
  { id: "food", name: "Food & drink", emoji: "🍜", sub: "Rice, tea, noodles…", words: [
    { id: "food:mǐfàn", hanzi: "米饭", pinyin: "mǐfàn", english: "rice", pronunciation: "mee-fahn", accepted: [] },
    { id: "food:chá", hanzi: "茶", pinyin: "chá", english: "tea", pronunciation: "chah", accepted: [] },
    { id: "food:shuǐ", hanzi: "水", pinyin: "shuǐ", english: "water", pronunciation: "shway", accepted: [] },
    { id: "food:miàntiáo", hanzi: "面条", pinyin: "miàntiáo", english: "noodles", pronunciation: "myen-tyow", accepted: ["noodle"] },
    { id: "food:kāfēi", hanzi: "咖啡", pinyin: "kāfēi", english: "coffee", pronunciation: "kah-fay", accepted: [] },
    { id: "food:píjiǔ", hanzi: "啤酒", pinyin: "píjiǔ", english: "beer", pronunciation: "pee-jyoh", accepted: [] },
    { id: "food:jī", hanzi: "鸡", pinyin: "jī", english: "chicken", pronunciation: "jee", accepted: [] },
    { id: "food:yú", hanzi: "鱼", pinyin: "yú", english: "fish", pronunciation: "yoo", accepted: [] },
    { id: "food:niúnǎi", hanzi: "牛奶", pinyin: "niúnǎi", english: "milk", pronunciation: "nyoh-nye", accepted: [] },
    { id: "food:píngguǒ", hanzi: "苹果", pinyin: "píngguǒ", english: "apple", pronunciation: "ping-gwaw", accepted: ["apples"] },
  ] },
  { id: "greetings", name: "Greetings & basics", emoji: "👋", sub: "Hello, thank you, sorry…", words: [
    { id: "greetings:nǐ hǎo", hanzi: "你好", pinyin: "nǐ hǎo", english: "hello", pronunciation: "nee how", accepted: ["hi"] },
    { id: "greetings:xièxie", hanzi: "谢谢", pinyin: "xièxie", english: "thank you", pronunciation: "shyeh-shyeh", accepted: ["thanks"] },
    { id: "greetings:zàijiàn", hanzi: "再见", pinyin: "zàijiàn", english: "goodbye", pronunciation: "dzye-jyen", accepted: ["bye","see you"] },
    { id: "greetings:duìbuqǐ", hanzi: "对不起", pinyin: "duìbuqǐ", english: "sorry", pronunciation: "dway-boo-chee", accepted: ["i'm sorry","i am sorry"] },
    { id: "greetings:qǐng", hanzi: "请", pinyin: "qǐng", english: "please", pronunciation: "ching", accepted: [] },
    { id: "greetings:zǎoshang hǎo", hanzi: "早上好", pinyin: "zǎoshang hǎo", english: "good morning", pronunciation: "dzow-shahng how", accepted: ["morning"] },
    { id: "greetings:wǎn'ān", hanzi: "晚安", pinyin: "wǎn'ān", english: "good night", pronunciation: "wahn-ahn", accepted: ["goodnight"] },
    { id: "greetings:bù kèqi", hanzi: "不客气", pinyin: "bù kèqi", english: "you're welcome", pronunciation: "boo kuh-chee", accepted: ["you are welcome","welcome"] },
    { id: "greetings:hǎo de", hanzi: "好的", pinyin: "hǎo de", english: "OK / sure", pronunciation: "how duh", accepted: ["ok","okay","sure"] },
    { id: "greetings:méi guānxi", hanzi: "没关系", pinyin: "méi guānxi", english: "no problem", pronunciation: "may gwahn-shee", accepted: ["no worries","it's ok","it's okay"] },
  ] },
  { id: "nouns", name: "Everyday nouns", emoji: "🏠", sub: "Home, friend, phone, dog…", words: [
    { id: "nouns:rén", hanzi: "人", pinyin: "rén", english: "person", pronunciation: "run", accepted: [] },
    { id: "nouns:jiā", hanzi: "家", pinyin: "jiā", english: "home / family", pronunciation: "jyah", accepted: ["home","family","house"] },
    { id: "nouns:shū", hanzi: "书", pinyin: "shū", english: "book", pronunciation: "shoo", accepted: [] },
    { id: "nouns:chē", hanzi: "车", pinyin: "chē", english: "car", pronunciation: "chuh", accepted: [] },
    { id: "nouns:mén", hanzi: "门", pinyin: "mén", english: "door", pronunciation: "mun", accepted: [] },
    { id: "nouns:qián", hanzi: "钱", pinyin: "qián", english: "money", pronunciation: "chyen", accepted: [] },
    { id: "nouns:shǒujī", hanzi: "手机", pinyin: "shǒujī", english: "mobile phone", pronunciation: "shoh-jee", accepted: ["phone","mobile","cell phone","cellphone"] },
    { id: "nouns:péngyou", hanzi: "朋友", pinyin: "péngyou", english: "friend", pronunciation: "pung-yoh", accepted: [] },
    { id: "nouns:gǒu", hanzi: "狗", pinyin: "gǒu", english: "dog", pronunciation: "goh", accepted: [] },
    { id: "nouns:māo", hanzi: "猫", pinyin: "māo", english: "cat", pronunciation: "maow", accepted: [] },
  ] },
  { id: "weather", name: "Weather", emoji: "🌦️", sub: "Sun, rain, wind, snow…", words: [
    { id: "weather:tiānqì", hanzi: "天气", pinyin: "tiānqì", english: "weather", pronunciation: "tyen-chee", accepted: [] },
    { id: "weather:tàiyáng", hanzi: "太阳", pinyin: "tàiyáng", english: "sun", pronunciation: "tye-yahng", accepted: ["sunshine"] },
    { id: "weather:yǔ", hanzi: "雨", pinyin: "yǔ", english: "rain", pronunciation: "yoo", accepted: [] },
    { id: "weather:xuě", hanzi: "雪", pinyin: "xuě", english: "snow", pronunciation: "shweh", accepted: [] },
    { id: "weather:fēng", hanzi: "风", pinyin: "fēng", english: "wind", pronunciation: "fung", accepted: [] },
    { id: "weather:yún", hanzi: "云", pinyin: "yún", english: "cloud", pronunciation: "yoon", accepted: ["clouds"] },
    { id: "weather:xià yǔ", hanzi: "下雨", pinyin: "xià yǔ", english: "it's raining", pronunciation: "shyah yoo", accepted: ["raining","it is raining","rainy"] },
    { id: "weather:xià xuě", hanzi: "下雪", pinyin: "xià xuě", english: "it's snowing", pronunciation: "shyah shweh", accepted: ["snowing","it is snowing"] },
    { id: "weather:qíngtiān", hanzi: "晴天", pinyin: "qíngtiān", english: "sunny day", pronunciation: "ching-tyen", accepted: ["sunny"] },
    { id: "weather:duōyún", hanzi: "多云", pinyin: "duōyún", english: "cloudy", pronunciation: "dwaw-yoon", accepted: [] },
  ] },
  { id: "food2", name: "More food & drink", emoji: "🥟", sub: "Dumplings, soup, pork, juice…", words: [
    { id: "food2:zhūròu", hanzi: "猪肉", pinyin: "zhūròu", english: "pork", pronunciation: "joo-roh", accepted: [] },
    { id: "food2:niúròu", hanzi: "牛肉", pinyin: "niúròu", english: "beef", pronunciation: "nyoh-roh", accepted: [] },
    { id: "food2:yángròu", hanzi: "羊肉", pinyin: "yángròu", english: "lamb", pronunciation: "yahng-roh", accepted: ["mutton"] },
    { id: "food2:jiǎozi", hanzi: "饺子", pinyin: "jiǎozi", english: "dumplings", pronunciation: "jyow-dzuh", accepted: ["dumpling"] },
    { id: "food2:tāng", hanzi: "汤", pinyin: "tāng", english: "soup", pronunciation: "tahng", accepted: [] },
    { id: "food2:miànbāo", hanzi: "面包", pinyin: "miànbāo", english: "bread", pronunciation: "myen-baow", accepted: [] },
    { id: "food2:jīdàn", hanzi: "鸡蛋", pinyin: "jīdàn", english: "egg", pronunciation: "jee-dahn", accepted: ["eggs"] },
    { id: "food2:shūcài", hanzi: "蔬菜", pinyin: "shūcài", english: "vegetables", pronunciation: "shoo-tsye", accepted: ["vegetable","veg","veggies"] },
    { id: "food2:shuǐguǒ", hanzi: "水果", pinyin: "shuǐguǒ", english: "fruit", pronunciation: "shway-gwaw", accepted: [] },
    { id: "food2:guǒzhī", hanzi: "果汁", pinyin: "guǒzhī", english: "juice", pronunciation: "gwaw-jrr", accepted: [] },
  ] },
  { id: "school", name: "School phrases", emoji: "🏫", sub: "Well done, quiet please, keep going…", words: [
    { id: "school:zuò de hǎo", hanzi: "做得好", pinyin: "zuò de hǎo", english: "well done", pronunciation: "dzwaw duh how", accepted: ["good job","good work"] },
    { id: "school:hěn hǎo", hanzi: "很好", pinyin: "hěn hǎo", english: "very good", pronunciation: "hun how", accepted: [] },
    { id: "school:búcuò", hanzi: "不错", pinyin: "búcuò", english: "good try / not bad", pronunciation: "boo-tswaw", accepted: ["good try","not bad","pretty good"] },
    { id: "school:nǐ zhēn bàng", hanzi: "你真棒", pinyin: "nǐ zhēn bàng", english: "you're brilliant", pronunciation: "nee jun bahng", accepted: ["you are brilliant","brilliant","you're great","you're amazing","amazing"] },
    { id: "school:jiāyóu", hanzi: "加油", pinyin: "jiāyóu", english: "keep going!", pronunciation: "jyah-yoh", accepted: ["keep going","add oil","come on","you can do it","go for it"] },
    { id: "school:wǒ wèi nǐ jiāo'ào", hanzi: "我为你骄傲", pinyin: "wǒ wèi nǐ jiāo'ào", english: "I'm proud of you", pronunciation: "waw way nee jyow-ow", accepted: ["i am proud of you","proud of you"] },
    { id: "school:qǐng ānjìng", hanzi: "请安静", pinyin: "qǐng ānjìng", english: "quiet please", pronunciation: "ching ahn-jing", accepted: ["please be quiet","be quiet","quiet","silence please"] },
    { id: "school:qǐng zuò", hanzi: "请坐", pinyin: "qǐng zuò", english: "please sit down", pronunciation: "ching dzwaw", accepted: ["sit down","sit down please","sit","take a seat"] },
    { id: "school:rènzhēn tīng", hanzi: "认真听", pinyin: "rènzhēn tīng", english: "listen carefully", pronunciation: "run-jun ting", accepted: ["listen"] },
    { id: "school:zài shì yī cì", hanzi: "再试一次", pinyin: "zài shì yī cì", english: "try again", pronunciation: "dzye shrr ee tsuh", accepted: ["have another go"] },
  ] },
  { id: "places", name: "Places around town", emoji: "📍", sub: "Park, station, bar, restaurant…", words: [
    { id: "places:gōngyuán", hanzi: "公园", pinyin: "gōngyuán", english: "park", pronunciation: "gohng-ywen", accepted: [] },
    { id: "places:huǒchēzhàn", hanzi: "火车站", pinyin: "huǒchēzhàn", english: "train station", pronunciation: "hwaw-chuh-jahn", accepted: ["station"] },
    { id: "places:jīchǎng", hanzi: "机场", pinyin: "jīchǎng", english: "airport", pronunciation: "jee-chahng", accepted: [] },
    { id: "places:jiǔbā", hanzi: "酒吧", pinyin: "jiǔbā", english: "bar", pronunciation: "jyoh-bah", accepted: ["pub"] },
    { id: "places:fànguǎn", hanzi: "饭馆", pinyin: "fànguǎn", english: "restaurant", pronunciation: "fahn-gwahn", accepted: [] },
    { id: "places:shāngdiàn", hanzi: "商店", pinyin: "shāngdiàn", english: "shop", pronunciation: "shahng-dyen", accepted: ["store"] },
    { id: "places:chāoshì", hanzi: "超市", pinyin: "chāoshì", english: "supermarket", pronunciation: "chow-shrr", accepted: [] },
    { id: "places:yīyuàn", hanzi: "医院", pinyin: "yīyuàn", english: "hospital", pronunciation: "ee-ywen", accepted: [] },
    { id: "places:xuéxiào", hanzi: "学校", pinyin: "xuéxiào", english: "school", pronunciation: "shweh-shyow", accepted: [] },
    { id: "places:yínháng", hanzi: "银行", pinyin: "yínháng", english: "bank", pronunciation: "yeen-hahng", accepted: [] },
  ] },
  { id: "time", name: "Time & days", emoji: "🕒", sub: "Today, tomorrow, days of the week…", words: [
    { id: "time:tiān", hanzi: "天", pinyin: "tiān", english: "day", pronunciation: "tyen", accepted: [] },
    { id: "time:xīngqī", hanzi: "星期", pinyin: "xīngqī", english: "week", pronunciation: "shing-chee", accepted: [] },
    { id: "time:yuè", hanzi: "月", pinyin: "yuè", english: "month", pronunciation: "yweh", accepted: [] },
    { id: "time:nián", hanzi: "年", pinyin: "nián", english: "year", pronunciation: "nyen", accepted: [] },
    { id: "time:jīntiān", hanzi: "今天", pinyin: "jīntiān", english: "today", pronunciation: "jin-tyen", accepted: [] },
    { id: "time:míngtiān", hanzi: "明天", pinyin: "míngtiān", english: "tomorrow", pronunciation: "ming-tyen", accepted: [] },
    { id: "time:zuótiān", hanzi: "昨天", pinyin: "zuótiān", english: "yesterday", pronunciation: "dzwaw-tyen", accepted: [] },
    { id: "time:xiànzài", hanzi: "现在", pinyin: "xiànzài", english: "now", pronunciation: "shyen-dzye", accepted: [] },
    { id: "time:zǎoshang", hanzi: "早上", pinyin: "zǎoshang", english: "morning", pronunciation: "dzow-shahng", accepted: [] },
    { id: "time:wǎnshang", hanzi: "晚上", pinyin: "wǎnshang", english: "evening", pronunciation: "wahn-shahng", accepted: [] },
    { id: "time:xīngqīyī", hanzi: "星期一", pinyin: "xīngqīyī", english: "Monday", pronunciation: "shing-chee-ee", accepted: [] },
    { id: "time:xīngqī'èr", hanzi: "星期二", pinyin: "xīngqī'èr", english: "Tuesday", pronunciation: "shing-chee-arr", accepted: [] },
    { id: "time:xīngqīsān", hanzi: "星期三", pinyin: "xīngqīsān", english: "Wednesday", pronunciation: "shing-chee-sahn", accepted: [] },
    { id: "time:xīngqīsì", hanzi: "星期四", pinyin: "xīngqīsì", english: "Thursday", pronunciation: "shing-chee-suh", accepted: [] },
    { id: "time:xīngqīwǔ", hanzi: "星期五", pinyin: "xīngqīwǔ", english: "Friday", pronunciation: "shing-chee-woo", accepted: [] },
    { id: "time:xīngqīliù", hanzi: "星期六", pinyin: "xīngqīliù", english: "Saturday", pronunciation: "shing-chee-lyoh", accepted: [] },
    { id: "time:xīngqītiān", hanzi: "星期天", pinyin: "xīngqītiān", english: "Sunday", pronunciation: "shing-chee-tyen", accepted: [] },
  ] },
  { id: "basics", name: "Essential basics", emoji: "💬", sub: "Yes, no, maybe, this, that, what…", words: [
    { id: "basics:shì", hanzi: "是", pinyin: "shì", english: "yes / it is", pronunciation: "shrr", accepted: [] },
    { id: "basics:bù shì", hanzi: "不是", pinyin: "bù shì", english: "no / it isn't", pronunciation: "boo shrr", accepted: [] },
    { id: "basics:kěnéng", hanzi: "可能", pinyin: "kěnéng", english: "maybe", pronunciation: "kuh-nung", accepted: [] },
    { id: "basics:duì", hanzi: "对", pinyin: "duì", english: "correct / right", pronunciation: "dway", accepted: [] },
    { id: "basics:bù", hanzi: "不", pinyin: "bù", english: "not", pronunciation: "boo", accepted: [] },
    { id: "basics:hěn", hanzi: "很", pinyin: "hěn", english: "very", pronunciation: "hun", accepted: [] },
    { id: "basics:yě", hanzi: "也", pinyin: "yě", english: "also / too", pronunciation: "yeh", accepted: [] },
    { id: "basics:hé", hanzi: "和", pinyin: "hé", english: "and", pronunciation: "huh", accepted: [] },
    { id: "basics:zhè", hanzi: "这", pinyin: "zhè", english: "this", pronunciation: "juh", accepted: [] },
    { id: "basics:nà", hanzi: "那", pinyin: "nà", english: "that", pronunciation: "nah", accepted: [] },
    { id: "basics:shénme", hanzi: "什么", pinyin: "shénme", english: "what", pronunciation: "shun-muh", accepted: [] },
    { id: "basics:shéi", hanzi: "谁", pinyin: "shéi", english: "who", pronunciation: "shay", accepted: [] },
    { id: "basics:nǎr", hanzi: "哪儿", pinyin: "nǎr", english: "where", pronunciation: "nar", accepted: [] },
    { id: "basics:kěyǐ", hanzi: "可以", pinyin: "kěyǐ", english: "can / may", pronunciation: "kuh-yee", accepted: [] },
    { id: "basics:wǒ bù zhīdào", hanzi: "我不知道", pinyin: "wǒ bù zhīdào", english: "I don't know", pronunciation: "waw boo jrr-daow", accepted: [] },
  ] },
  { id: "home", name: "Home & belongings", emoji: "🛋️", sub: "Room, table, keys, clothes…", words: [
    { id: "home:fángjiān", hanzi: "房间", pinyin: "fángjiān", english: "room", pronunciation: "fahng-jyen", accepted: [] },
    { id: "home:zhuōzi", hanzi: "桌子", pinyin: "zhuōzi", english: "table", pronunciation: "jwaw-dzuh", accepted: [] },
    { id: "home:yǐzi", hanzi: "椅子", pinyin: "yǐzi", english: "chair", pronunciation: "yee-dzuh", accepted: [] },
    { id: "home:chuáng", hanzi: "床", pinyin: "chuáng", english: "bed", pronunciation: "chwahng", accepted: [] },
    { id: "home:chuānghu", hanzi: "窗户", pinyin: "chuānghu", english: "window", pronunciation: "chwahng-hoo", accepted: [] },
    { id: "home:yàoshi", hanzi: "钥匙", pinyin: "yàoshi", english: "key", pronunciation: "yow-shrr", accepted: ["keys"] },
    { id: "home:bāo", hanzi: "包", pinyin: "bāo", english: "bag", pronunciation: "baow", accepted: [] },
    { id: "home:yīfu", hanzi: "衣服", pinyin: "yīfu", english: "clothes", pronunciation: "ee-foo", accepted: ["clothing"] },
    { id: "home:xié", hanzi: "鞋", pinyin: "xié", english: "shoes", pronunciation: "shyeh", accepted: ["shoe"] },
    { id: "home:diànnǎo", hanzi: "电脑", pinyin: "diànnǎo", english: "computer", pronunciation: "dyen-now", accepted: ["PC"] },
  ] },
  { id: "people", name: "People", emoji: "👥", sub: "Family, work and everyday people", words: [
    { id: "people:māma", hanzi: "妈妈", pinyin: "māma", english: "mother", pronunciation: "mah-ma", accepted: ["mum", "mom"] },
    { id: "people:bàba", hanzi: "爸爸", pinyin: "bàba", english: "father", pronunciation: "bah-ba", accepted: ["dad"] },
    { id: "people:lǎoshī", hanzi: "老师", pinyin: "lǎoshī", english: "teacher", pronunciation: "laow-shrr", accepted: [] },
    { id: "people:xuésheng", hanzi: "学生", pinyin: "xuésheng", english: "student", pronunciation: "shweh-shung", accepted: [] },
    { id: "people:tóngshì", hanzi: "同事", pinyin: "tóngshì", english: "colleague", pronunciation: "tohng-shrr", accepted: ["coworker", "co-worker"] },
    { id: "people:háizi", hanzi: "孩子", pinyin: "háizi", english: "child", pronunciation: "high-dzuh", accepted: ["kid"] },
    { id: "people:nánrén", hanzi: "男人", pinyin: "nánrén", english: "man", pronunciation: "nan-run", accepted: [] },
    { id: "people:nǚrén", hanzi: "女人", pinyin: "nǚrén", english: "woman", pronunciation: "nyoo-run", accepted: [] },
    { id: "people:yīshēng", hanzi: "医生", pinyin: "yīshēng", english: "doctor", pronunciation: "ee-shung", accepted: [] },
    { id: "people:fúwùyuán", hanzi: "服务员", pinyin: "fúwùyuán", english: "server", pronunciation: "foo-woo-ywen", accepted: ["waiter", "waitress"] },
  ] },
  { id: "directions", name: "Position & direction", emoji: "🧭", sub: "Up, down, left, right, near…", words: [
    { id: "directions:shàng", hanzi: "上", pinyin: "shàng", english: "up / above", pronunciation: "shahng", accepted: ["up", "above", "on"] },
    { id: "directions:xià", hanzi: "下", pinyin: "xià", english: "down / below", pronunciation: "shyah", accepted: ["down", "below", "under"] },
    { id: "directions:zuǒbian", hanzi: "左边", pinyin: "zuǒbian", english: "left", pronunciation: "dzwaw-byen", accepted: ["left side"] },
    { id: "directions:yòubian", hanzi: "右边", pinyin: "yòubian", english: "right", pronunciation: "yoh-byen", accepted: ["right side"] },
    { id: "directions:lǐmiàn", hanzi: "里面", pinyin: "lǐmiàn", english: "inside", pronunciation: "lee-myen", accepted: ["in"] },
    { id: "directions:wàimiàn", hanzi: "外面", pinyin: "wàimiàn", english: "outside", pronunciation: "wye-myen", accepted: ["out"] },
    { id: "directions:qiánmiàn", hanzi: "前面", pinyin: "qiánmiàn", english: "in front", pronunciation: "chyen-myen", accepted: ["front", "ahead"] },
    { id: "directions:hòumiàn", hanzi: "后面", pinyin: "hòumiàn", english: "behind", pronunciation: "hoh-myen", accepted: ["at the back", "back"] },
    { id: "directions:jìn", hanzi: "近", pinyin: "jìn", english: "near", pronunciation: "jin", accepted: ["close"] },
    { id: "directions:yuǎn", hanzi: "远", pinyin: "yuǎn", english: "far", pronunciation: "ywen", accepted: ["far away"] },
  ] }
];
window.MANDARIN_WORDS = window.MANDARIN_TOPICS.flatMap(topic => topic.words.map(word => ({ ...word, topic: topic.id })));
